### ISSUE TITLE
密码是在哪儿添加的 ，没找到地方

### ISSUE THREAD

**Issue by 94zuocom** [hocgin/yourself-email#4]

**Comment by hocgin** [comment]
添加登录和权限参考: https://github.com/hocgin/yourself-email/blob/main/pages/scripts/add_super_admin.sql
数据库是 Cloudflare 的 D1，具体操作 D1 的方式你可以看 Cloudflare 官方文档。

如果你是用现有的一键构建脚本，会自动将你设置的“CLOUDFLARE_EMAIL_ADDRESS”设置为超级管理员账号。在访问邮箱站点的时候使用这个账号登录就可以。
